[project]
name = "no-mcp-server"
version = "0.1.0"
description = "An unofficial MCP server to interact with No-as-a-Service"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.5.2",
    "requests>=2.32.3",
]
